name: Build

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build-exe:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pywebview pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --noconsole --name SecureMessenger client.py
      - uses: actions/upload-artifact@v4
        with:
          name: SecureMessenger-Windows
          path: dist\SecureMessenger.exe

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Сборка APK
        uses: AddyMendoza/webview-apk-builder@v1
        with:
          app_name: SecureMessenger
          app_url: https://твой-сервер.com
          app_package: com.securemessenger
          app_version: 1.0.0
          orientation: portrait
          enable_javascript: true
          enable_microphone: true
          enable_camera: true
          enable_dom_storage: true

      - uses: actions/upload-artifact@v4
        with:
          name: SecureMessenger-Android
          path: app-release.apk
