name: Build

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build-exe:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: pip install pywebview pyinstaller
      - name: Сборка EXE
        run: pyinstaller --onefile --noconsole --name SecureMessenger client.py
      - name: Загрузить EXE
        uses: actions/upload-artifact@v4
        with:
          name: SecureMessenger-Windows
          path: dist\SecureMessenger.exe

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка официального инструмента
        run: npm install -g pwabuilder-cli

      - name: Сборка APK
        run: |
          pwabuilder build android --url https://твой-сервер.com \
            --name SecureMessenger \
            --packageId com.securemessenger \
            --version 1.0.0 \
            --display standalone \
            --orientation portrait \
            --enableCamera true \
            --enableMicrophone true

      - name: Загрузить APK
        uses: actions/upload-artifact@v4
        with:
          name: SecureMessenger-Android
          path: output/android/*.apk
